# Module 1

## Introduction to Positive Leadership

<p style = "text-align: right; font-size: 8pt; "><i>`Foster Blair, May 5, 2020 @ 5 PM - 6 PM`</i></p>

> In my practice of coaching leaders, and I started out with a very small niche, and that was with lawyers, and then I ventured over into healthcare and financial services, and what I found when I was changing industries, coaching leaders regardless of what industry they are in you can serve them very well and not necessarily have a background in that. If we start with the assumption that we learned in foundations, that everyone that we coach is creative, resourceful, and whole, and they should have all the answers. You as the coach are there just to provide guidance and support for them, that is to say, you don’t need an expertise in a particular area to coach that particular leader. You don’t have to understand the full background of the business when you are coaching that leader.


There are many definitions of Leadership and probably even more theories and ideas about what constitutes a good leader and which steps a leader must follow to be a good or great leader.

<p style = "text-align: left; font-size: 16pt; "><b>Leadership Dimensions</b></p> (James Kouzes and Barry Posner: The Leadership Challenge)

>These are the types of things that a leader must be adept at in order to be a good leader.

+ <p style = "text-align: left; font-size: 13pt; ">Framing a vision, mission, and strategy</p>
+ <p style = "text-align: left; font-size: 13pt; ">Developing and managing systems</p>
+ <p style = "text-align: left; font-size: 13pt; ">Setting expectations, priorities, and direction</p>
+ <p style = "text-align: left; font-size: 13pt; ">Delegating work and decisions</p>
+ <p style = "text-align: left; font-size: 13pt; ">Communicating</p>
+ <p style = "text-align: left; font-size: 13pt; ">Influencing</p>
+ <p style = "text-align: left; font-size: 13pt; ">Providing and seeking feedback</p>

> There are a lot of different things that a leader must be adept at but they can’t be adept at all of these. So setting expectations, priorities, and directions for their teams, being able to communicate well, being able to delegate work and make sound and quick decisions, having the ability to influence, are all marks of a good leader. Providing and seeking feedback, this is critical especially when it comes to coaching. 

> For those leaders that aren’t able to receive feedback well, you will find that they are very hard to coach.

+ <p style = "text-align: left; font-size: 13pt; ">Building Teams</p>

> What will happen often times is that a leader will have a team, but some leaders do not know how to attract talent and they will hire people just like themselves, and that can be a handicap.

> A good leader will look at what the needs are of the business and what talent they possess on their teams and what they will do is to search out talent that rounds out the team to make them more efficient and productive.

+ <p style = "text-align: left; font-size: 13pt; ">Developing people</p>
+ <p style = "text-align: left; font-size: 13pt; ">Building and Maintaining relationships</p>

> Building and maintaining a relationships is key for great leaders. Probably about 50% of the work of a leader is to maintain, build, nurture, and cement the relationship they engender. This is a tough one for most.

+ <p style = "text-align: left; font-size: 13pt; ">Recruiting talent</p>
+ <p style = "text-align: left; font-size: 13pt; ">Problem solving/decision making</p>
+ <p style = "text-align: left; font-size: 13pt; ">Using political savvy</p>
+ <p style = "text-align: left; font-size: 13pt; ">Creating meaning and purpose</p>

> You know answering the why especially for their team that goes hand in hand with the communication piece, on being able to convey the meaning on why they are doing the work that they are doing and the reasons behind that.

“Leadership is not about who you are, it’s about what you do.”

<p style = "text-align: left; font-size: 16pt; "><b>The five practices of exemplary leadership</b></p>

+ <p style = "text-align: left; font-size: 13pt; ">Model the Way</p>

> They must basically live out what they are talking to their teams.

+ <p style = "text-align: left; font-size: 13pt; ">Inspire a Shared vision</p>
+ <p style = "text-align: left; font-size: 13pt; ">Challenge the Process</p>

> They need to challenge what is happening, make sure they are always improving and innovating.

+ <p style = "text-align: left; font-size: 13pt; ">Enable Others to Act</p>

> Empowering their team members, making sure that they work with others, and give them space to grow and to work on their own.

+ <p style = "text-align: left; font-size: 13pt; ">Encourage the Heart</p>

> You have to be able to touch on the meaningfulness of the work that your people are doing

<p style = "text-align: left; font-size: 16pt; "><b>The Hierarchy of Sustained Change</b></p> (Ted Middleburg; Transformational Executive Coaching)

+ <p style = "text-align: left; font-size: 13pt; ">Establishing safety and trust</p>
+ <p style = "text-align: left; font-size: 13pt; ">Building relationships</p>

> <i>Examples of building relationships:</i>
Sara Fay - I certainly have for sure, I am thinking of my former leader actually, and her ability to build relationships and connect through empathy with people pretty rapidly was so impressive and it would create this bond with all different types of people from all different types of organizations that would continuously come back and help her in certain ways throughout her career. 

> And when you saw her in action, what did you see her do that made her effective in that skill.

> Sara Fay - A couple of things, I would say 1) her body language, a lot of the non-verbals, but also just her, I will never forget she always told me 2) whenever you meet someone in a business setting she would always say <b>make sure you learn one thing about them that has nothing to do with the business or why you are meeting with them to start to build a personal relationship with the person.</b> 

> Most leaders will put others first. People like to hear themselves talk a lot, if you are a leader in that position of wanting to build relationships,it is very good for the other person to take the lead. When I start to build relationships, I do try to find out about that one or two things that is important to them and I speak last, because I want to show interest in that individual that I am looking to build that relationship with. 

+ <p style = "text-align: left; font-size: 13pt; ">Enhancing the feedback environment</p>
+ <p style = "text-align: left; font-size: 13pt; ">Thinking in systems</p>

> When you are working with leaders it may be helpful to silo certain areas so that they are thinking in systems. So, it is more of a robotic way of looking at things to help them focus, on taking small things at a time to focus on so that they can get through it.

+ <p style = "text-align: left; font-size: 13pt; ">Sustaining change</p>

> Sustaining change is towards the end of the coaching engagement. When coaching with leaders there are behaviors that they may need to change or work on or improve. There is a <b><u>role play</u></b> that you would use with them as a coach to practice. Practice this with your coach, so you can improve it or perfect it, and then go out to the work world or the business environment, and implement it, and then working with them continually so the change that they are making and behavior is sustained.

> <i>Example of role playing:</i>
When I am working with a leader, we clearly outline a development plan of the goals they would like to achieve, and then once we have identified those goals and we take some assessments and then there may be some behaviors or there may be some issues that they bring to me that they are having with their colleagues, with their teams. 

> I will ask the leader, well, how do you show up in that particular situation or scenario?

> I would ask how is that working for you or how did that work out for you?

> If they mention that it didn’t work so well for them, well, <b>how could we change things for the better,</b> and so I will allow them to come up with a number of practices, a number of ideas which to implement the change behavior and then what we would do is role play in a very safe, private environment. I would help and coach them through that before they would take that to their teams or the other individuals, because a lot of times, what will present itself it is not very comfortable for them to do that, because if it was they would have been implementing that in the first place. It gives them an opportunity to get comfortable with the new or changed behavior.

> And, I could say, what I would do is the next time you interact with Melanie I want you to employ some of the strategies that we developed while we were in our coaching session. 

> Then in the subsequent coaching session, I would follow up with them to say how did it work out with Melanice, was there a different response to your change behavior. Then, we would go from there.



<p style = "text-align: left; font-size: 16pt; "><b>The most effective leaders are:</b></p>  (Tom Rath and Barry Conchie  (Strengths Based Leadership)

+ <p style = "text-align: left; font-size: 13pt; ">Always investing in strengths</p>

> Now, when we talked about all these dimensions of a leader there are going to be some things that the leader will excel at and there will be some of the other characteristics that there is an area for development. That is where we come in as coaches to help with building up their strengths, and I think you have to take them in tandem. I know that we focus on strengths, but we should never ignore the areas for development. But, I don’t know if we should spend too much time on those areas, because there is only a short window on return on investment. But, these are some areas where you can actually work with your leaders on developing them better as positive leaders.

> VIA is something that you can use with your clients and helping them show up more positively in their work. A most effective leader always invests in their strengths and that is what you would want to work with your clients, but there is also a tendency, especially with great leaders, where they <u><b>overuse a strength and then it becomes a weakness</u></b>, so, you just have to monitor that from time to time when working with your clients,

+ <p style = "text-align: left; font-size: 13pt; ">Surround themselves with the right people and then maximize their team</p>

> A leader, to be effective will surround themselves with such a diverse group of individuals that will add value to their team. So that they can maximize the results that they are seeking.

+ <p style = "text-align: left; font-size: 13pt; ">Understand their followers needs</p>

>They need to be empathic. They need to check in with their team often. A lot of times leaders sit in ivory towers and they miss the connection with the people that report to them. Also if you have yes people or lead in such a way that people are scared to speak up you may miss that connection of what your followers really need and want from the leader.
